import { analyze, formatDimension } from './core/index.ts';
import type { Analysis, Project, TraceNode } from './core/types.ts';
import { PRESETS } from './presets.ts';
import { importProject, exportProject, exportReport, escapeHtml as esc } from './project.ts';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const storage={get:(k:string)=>{try{return localStorage.getItem(k);}catch{return null;}},set:(k:string,v:string)=>{try{localStorage.setItem(k,v);return true;}catch{return false;}},remove:(k:string)=>{try{localStorage.removeItem(k);}catch{/* Storage can be unavailable in private modes. */}}};
let lang=storage.get('dimsleuth.language')==='zh'?'zh':'en';
let project:Project=structuredClone(PRESETS[0].project),presetId='kinematics',remember=false,selected:string|null=null,analysis:Analysis;
let restored=false,revision=0,importRequest=0;
const saved=storage.get('dimsleuth.draft.v1');if(saved){try{project=importProject(saved);remember=true;presetId='';restored=true;}catch{storage.remove('dimsleuth.draft.v1');}}
const t=(en:string,zh:string)=>lang==='zh'?zh:en;
function shell(){
 revision++;
 document.documentElement.lang=lang==='zh'?'zh-CN':'en';
 $('app').innerHTML=`<header class="topbar"><a class="brand" href="#workspace" aria-label="DimSleuth workspace"><span class="brand-mark">d<span>?</span></span><span>DimSleuth<small>${t('DIMENSIONAL DEBUGGER','物理量纲调试器')}</small></span></a><div class="header-actions"><span class="local-pill">${t('LOCAL BY DESIGN','本地运算')}</span><button id="language" class="quiet" lang="${lang==='en'?'zh-CN':'en'}">${lang==='en'?'中文':'English'}</button><button id="help" class="quiet">${t('Syntax & help','语法与帮助')}</button></div></header>
 <main id="workspace"><section class="intro"><div><p class="eyebrow">${t('FOLLOW THE UNITS. FIND THE MISTAKE.','沿着量纲，找到错误。')}</p><h1>${t('Every operation leaves a trail.','每一步运算，都有迹可循。')}</h1><p>${t('Debug the dimensions of a formula, one operation at a time.','逐步追踪公式，定位量纲不一致的运算。')}</p></div><div class="intro-note"><span>01 / 03</span>${t('Write a formula','输入公式')}<i>·</i><span>02 / 03</span>${t('Define units','定义单位')}<i>·</i><span>03 / 03</span>${t('Trace the error','追踪错误')}</div></section>
 <nav class="presets" aria-label="${t('Physics examples','物理示例')}">${PRESETS.map(p=>`<button data-preset="${p.id}" class="preset ${p.id===presetId?'active':''}">${esc(lang==='en'?p.title:p.titleZh)}</button>`).join('')}</nav>
 <div class="workbench"><section class="editor panel" aria-labelledby="input-heading"><div class="panel-heading"><span class="section-number">01</span><h2 id="input-heading">${t('Your formula','你的公式')}</h2><span class="micro">${t('EDIT','可编辑')}</span></div><p id="preset-note" class="muted"></p><label for="title">${t('Project title','项目标题')}</label><input id="title" maxlength="120" value="${esc(project.title)}"><label for="formula">${t('Expression or equation','表达式或等式')}</label><textarea id="formula" rows="3" maxlength="2048" spellcheck="false" autocapitalize="off" autocomplete="off">${esc(project.formula)}</textarea><div class="input-actions"><span class="micro">${t('Explicit ×: use * · Ctrl/⌘ Enter','乘法请用 * · Ctrl/⌘ Enter')}</span><button id="check" class="primary">${t('Check dimensions','检查量纲')}</button></div><div class="symbols-head"><h3>${t('Symbol units','符号单位')}</h3><button id="add-symbol" class="text-button">+ ${t('Add','添加')}</button></div><div id="symbols"></div><p class="hint">${t('Use units such as m, s, kg, N, J, V or kg/m^3. Use 1 for dimensionless. Case matters.','可用 m、s、kg、N、J、V 或 kg/m^3。无量纲填 1。区分大小写。')}</p><div class="storage-row"><label class="checkbox"><input type="checkbox" id="remember" ${remember?'checked':''}>${t('Remember draft in this browser','在此浏览器保存草稿')}</label><button id="forget" class="text-button">${t('Clear saved','清除保存')}</button></div><p class="hint">${t('Your formula stays on this device. No accounts, APIs, or analytics in the app.','公式只在此设备计算。应用无账户、API 或分析跟踪。')}</p></section>
 <section class="trace-panel" aria-labelledby="trace-heading"><div class="panel-heading"><span class="section-number">02</span><h2 id="trace-heading">${t('The dimension trail','量纲轨迹')}</h2><span id="step-count" class="micro"></span></div><div id="result-banner"><div id="status" role="status" aria-live="polite"></div><p id="result-summary"></p></div><div class="source-header"><span class="micro">${t('SOURCE · SELECT A STEP TO LOCATE IT','源码 · 选择步骤定位')}</span></div><div id="source" class="source-code" aria-label="${t('Highlighted expression','高亮表达式')}"></div><div id="diagnostics"></div><div id="repair-wrap"><button id="repair"></button><p>${t('This repairs dimensions only. The physical equation may still need a coefficient, such as 1/2.','仅修复量纲。实际物理公式仍可能需要 1/2 等系数。')}</p></div><div id="trace" class="trace-list"></div></section>
 <aside class="inspector-panel panel" aria-labelledby="detail-heading"><div class="panel-heading"><span class="section-number">03</span><h2 id="detail-heading">${t('Under the lens','运算详情')}</h2></div><div id="inspector"></div><div class="comparison"><h3>${t('Seven SI dimensions','七个 SI 基本量纲')}</h3><p class="hint">${t('Exact rational exponents · left vs right','精确有理数指数 · 左侧与右侧')}</p><div id="vectors"></div></div><aside class="caveat"><span class="caveat-icon">!</span><div><strong>${t('Consistent ≠ physically correct','量纲一致 ≠ 物理正确')}</strong><p>${t('Dimensions cannot check signs, coefficients, assumptions, or numerical values. This is a debugging aid, not a proof.','量纲无法检查正负号、系数、假设或数值。这是调试工具，不是物理证明。')}</p></div></aside></aside></div>
 <div class="project-tools"><span>${t('KEEP YOUR WORK','保存你的工作')}</span><button id="export-project">${t('Export project .json','导出项目 .json')}</button><button id="import-project">${t('Import project','导入项目')}</button><button id="export-report">${t('Export trace report','导出追踪报告')}</button><input type="file" id="file" accept="application/json,.json" hidden><span id="notice" role="status" aria-live="polite"></span></div>
 <details id="guide"><summary>${t('Syntax, unit catalog & limitations','语法、单位与限制')}</summary><div class="guide-grid"><div><h3>${t('Write it explicitly','显式书写')}</h3><p>+ - * / ^ ( ) = · sqrt(x) · sin(x) · cos(x) · tan(x) · exp(x) · log(x)</p><p>${t('Multiplication is explicit: v*t, not vt or v t. A single = is optional. pi and e are dimensionless constants. Variable names use ASCII letters, digits and underscores, starting with a letter.','显式使用乘号：v*t，不能写 vt 或 v t。可以包含一个 =。pi 和 e 是无量纲常数。变量名以英文字母开头，可含数字和下划线。')}</p><p>${t('Power is right-associative and binds tighter than unary: -x^2 means -(x^2). Exponents must be numeric constant arithmetic, such as x^(1/2).','幂运算从右向左，优先于一元负号：-x^2 表示 -(x^2)。指数必须是数值常量算式，例如 x^(1/2)。')}</p></div><div><h3>${t('Dimensions, not conversions','量纲检查，不做数值换算')}</h3><p>${t('Base units: m, kg, s, A, K, mol, cd. Derived units include Hz, N, Pa, J, W, C, V, F, ohm, S, Wb, T, H, lm, lx. rad and sr are dimensionless.','基本单位：m、kg、s、A、K、mol、cd。导出单位包括 Hz、N、Pa、J、W、C、V、F、ohm、S、Wb、T、H、lm、lx。rad 和 sr 为无量纲。')}</p><p>${t('C means coulomb. Celsius/Fahrenheit and offset-temperature arithmetic are unsupported; use K for temperature dimensions. No numeric conversions, symbolic solver, implicit units, or arbitrary functions.','C 表示库仑。摄氏/华氏温度和带偏移温标的运算不支持；温度量纲请用 K。不做数值换算、符号求解，不支持隐式单位或任意函数。')}</p><p>${t('Limits: 2,048 formula characters, 512 tokens, nesting 64, 128 symbols, 128 characters per unit. Detailed parser diagnostics and trace rules are currently in English.','限制：公式 2,048 字符、512 个词元、64 层嵌套、128 个符号，每个单位 128 字符。详细解析诊断及运算规则当前使用英文。')}</p></div></div></details><footer><span>DimSleuth <span class="micro">v0.1.0</span></span><span>${t('Small language. Transparent rules. No black box.','小而明确的语法，透明可查的规则。')}</span></footer></main>`;
 renderSymbols();bind();run();if(restored){notice(t('Restored the draft saved in this browser.','已恢复此浏览器保存的草稿。'));restored=false;}
}
function renderSymbols(){
 $('symbols').innerHTML=project.symbols.map((s,i)=>`<div class="symbol-row"><label class="sr-only" for="symbol-${i}">${t('Symbol','符号')} ${i+1}</label><input id="symbol-${i}" data-name="${i}" value="${esc(s.name)}" maxlength="32" spellcheck="false" aria-label="${t('Symbol name','符号名称')} ${i+1}"><span>:</span><label class="sr-only" for="unit-${i}">${t('Unit','单位')} ${esc(s.name)}</label><input id="unit-${i}" data-unit="${i}" value="${esc(s.unit)}" maxlength="128" spellcheck="false" aria-label="${t('Unit of','单位')} ${esc(s.name)}"><button data-remove="${i}" class="remove" aria-label="${t('Remove','删除')} ${esc(s.name)}">×</button></div>`).join('');
}
let timer:ReturnType<typeof setTimeout>|undefined;
function sync(){project.formula=$<HTMLTextAreaElement>('formula').value;project.title=$<HTMLInputElement>('title').value;project.symbols=project.symbols.map((s,i)=>({name:$<HTMLInputElement>(`symbol-${i}`)?.value??s.name,unit:$<HTMLInputElement>(`unit-${i}`)?.value??s.unit}));}
function queue(){revision++;clearTimeout(timer);timer=setTimeout(run,180);}
function save(){if(remember){try{if(!storage.set('dimsleuth.draft.v1',exportProject(project)))notice(t('Browser storage is unavailable. Export your project to keep it.','浏览器存储不可用，请导出项目。'));}catch{notice(t('Draft not saved: fix invalid symbol names first.','草稿未保存：请先修正无效符号名。'));}}}
function run(){clearTimeout(timer);sync();analysis=analyze(project.formula,project.symbols);selected=analysis.diagnostics.find(d=>d.nodeId)?.nodeId??analysis.root??analysis.rhs??analysis.lhs??analysis.nodes.at(-1)?.id??null;renderResults();save();}
function renderResults(){
 const valid=analysis.status==='consistent',invalid=analysis.status==='invalid';
 $('result-banner').className=valid?'good':invalid?'invalid':'bad';
 $('status').textContent=valid?t('Dimensionally consistent','量纲一致'):invalid?t('Invalid input','输入无效'):t('Incompatible dimensions','量纲不一致');
 $('result-summary').textContent=valid?t('All checked operations agree. Physical correctness is still yours to verify.','已检查的运算量纲一致，仍需验证物理正确性。'):t(`${analysis.diagnostics.length} issue${analysis.diagnostics.length===1?'':'s'} found. Follow the highlighted operation.`,`发现 ${analysis.diagnostics.length} 个问题，请检查高亮运算。`);
 $('step-count').textContent=t(`${analysis.nodes.length} STEPS`,`${analysis.nodes.length} 步`);
 const p=PRESETS.find(p=>p.id===presetId);$('preset-note').textContent=p?(lang==='en'?p.description:p.descriptionZh):t('Your own formula. Every input is analyzed locally.','自定义公式。所有输入都在本地分析。');
 $('diagnostics').innerHTML=analysis.diagnostics.map((d,i)=>`<button class="diagnostic" data-diagnostic="${i}"><span>!</span><span>${esc(d.message)}<small>${d.span.start===d.span.end?t('Symbol configuration','符号配置'):t('Characters','字符')+' '+(d.span.start+1)+'–'+d.span.end}${d.symbol?' · '+esc(d.symbol):''}</small></span></button>`).join('');
 const canRepair=!!p?.repair&&project.formula===p.project.formula;$('repair-wrap').hidden=!canRepair;$('repair').textContent=t('Try the missing t²','试试补上 t²');
 $('trace').innerHTML=analysis.nodes.map((n,i)=>`<button class="trace-node ${n.status}" data-node="${esc(n.id)}" aria-pressed="${n.id===selected}"><span class="node-index">${String(i+1).padStart(2,'0')}</span><span class="node-expression">${esc(project.formula.slice(n.span.start,n.span.end))}<small>${esc(n.kind==='symbol'?t('defined symbol','已定义符号'):n.kind==='number'?t('pure number','纯数'):n.label)}</small></span><span class="node-dimension">${esc(formatDimension(n.dimension))}</span><span class="node-state" aria-label="${esc(n.status)}">${n.status==='valid'?'✓':n.status==='error'?'!':'·'}</span></button>`).join('')||`<p class="empty">${t('Enter a valid expression to build its trace.','输入有效表达式以生成追踪。')}</p>`;
 renderSelection();renderVectors();
}
function sourceHighlight(start:number,end:number){$('source').innerHTML=esc(project.formula.slice(0,start))+`<mark>${esc(project.formula.slice(start,end))||' '}</mark>`+esc(project.formula.slice(end));}
function renderSelection(){
 const n=analysis.nodes.find(n=>n.id===selected);document.querySelectorAll<HTMLElement>('[data-node]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.node===selected)));
 if(!n){const d=analysis.diagnostics[0];if(d)sourceHighlight(d.span.start,d.span.end);else $('source').textContent=project.formula||t('Your formula appears here','公式将显示在这里');$('inspector').innerHTML=`<div class="inspector-empty">${t('Select a trace step to inspect its rule and dimensional inputs.','选择追踪步骤，查看规则与输入量纲。')}</div>`;return;}
 sourceHighlight(n.span.start,n.span.end);
 const children=n.children.map(id=>analysis.nodes.find(c=>c.id===id)).filter((v):v is TraceNode=>!!v);
 $('inspector').innerHTML=`<span class="detail-label">${t('SELECTED OPERATION','所选运算')}</span><div class="selected-expression">${esc(project.formula.slice(n.span.start,n.span.end))}</div><div class="detail-status ${n.status}">${esc(n.status==='valid'?t('Valid dimension','量纲有效'):n.status==='error'?t('Dimension conflict','量纲冲突'):t('Blocked by an earlier error','受前序错误阻断'))}</div>${children.length?`<h4>${t('Inputs','输入')}</h4><div class="operand-list">${children.map(c=>`<button data-node="${esc(c.id)}"><code>${esc(project.formula.slice(c.span.start,c.span.end))}</code><span>${esc(formatDimension(c.dimension))}</span></button>`).join('')}</div>`:''}<h4>${t('The rule','运算规则')}</h4><p class="rule-text">${esc(n.rule)}</p><h4>${t('Output dimension','输出量纲')}</h4><div class="dimension-output">${esc(formatDimension(n.dimension))}</div><p class="hint">${t('Source characters','源字符')} ${n.span.start+1}–${n.span.end}</p>`;
}
function renderVectors(){
 const lhs=analysis.nodes.find(n=>n.id===(analysis.lhs??analysis.root));const rhs=analysis.nodes.find(n=>n.id===analysis.rhs);const names=lang==='en'?['Length','Mass','Time','Current','Temperature','Amount','Luminous']:['长度','质量','时间','电流','温度','物质的量','发光强度'];const marks=['L','M','T','I','Θ','N','J'];
 $('vectors').innerHTML=`<div class="vector-heading"><span>${t('Dimension','量纲')}</span><span>${analysis.rhs?'LHS':t('Result','结果')}</span><span>${analysis.rhs?'RHS':'—'}</span></div>`+names.map((name,i)=>{const a=lhs?.dimension?.[i]??'?',b=rhs?.dimension?.[i]??(analysis.rhs?'?':'—');return `<div class="vector-row ${analysis.rhs&&a!==b?'different':''}"><span><b>${marks[i]}</b>${name}</span><code>${esc(a)}</code><code>${esc(b)}</code></div>`;}).join('')+`<p class="hint">${t('J here denotes luminous intensity, not joules. ? means an unresolved dimension.','这里的 J 表示发光强度，并非焦耳。? 表示量纲尚未确定。')}</p>`;
}
function notice(message:string){$('notice').textContent=message;}
function load(p:Project,id=''){project=structuredClone(p);presetId=id;selected=null;shell();}
function download(text:string,name:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bind(){
 $('language').onclick=()=>{sync();lang=lang==='en'?'zh':'en';storage.set('dimsleuth.language',lang);shell();};
 $('help').onclick=()=>{const g=$<HTMLDetailsElement>('guide');g.open=!g.open;if(g.open)g.scrollIntoView({behavior:'smooth',block:'nearest'});};
 $('check').onclick=run;$('formula').oninput=queue;$('title').oninput=queue;
 $('formula').onkeydown=(event)=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();run();}};
 $('symbols').oninput=queue;
 $('symbols').onclick=(event)=>{const button=(event.target as HTMLElement).closest<HTMLElement>('[data-remove]');if(button){revision++;sync();project.symbols.splice(Number(button.dataset.remove),1);renderSymbols();run();}};
 $('add-symbol').onclick=()=>{revision++;sync();if(project.symbols.length>=128){notice(t('Maximum 128 symbols.','最多 128 个符号。'));return;}let i=1;while(project.symbols.some(s=>s.name===`q${i}`))i++;project.symbols.push({name:`q${i}`,unit:'1'});renderSymbols();$<HTMLInputElement>(`symbol-${project.symbols.length-1}`).focus();run();};
 document.querySelectorAll<HTMLElement>('[data-preset]').forEach(el=>el.onclick=()=>{const p=PRESETS.find(p=>p.id===el.dataset.preset);if(p)load(p.project,p.id);});
 $('trace').onclick=(event)=>{const el=(event.target as HTMLElement).closest<HTMLElement>('[data-node]');if(el){selected=el.dataset.node!;renderSelection();}};
 $('inspector').onclick=(event)=>{const el=(event.target as HTMLElement).closest<HTMLElement>('[data-node]');if(el){selected=el.dataset.node!;renderSelection();}};
 $('diagnostics').onclick=(event)=>{const el=(event.target as HTMLElement).closest<HTMLElement>('[data-diagnostic]');if(el){const d=analysis.diagnostics[Number(el.dataset.diagnostic)];selected=d.nodeId??null;renderSelection();sourceHighlight(d.span.start,d.span.end);}};
 $('repair').onclick=()=>{sync();const p=PRESETS.find(p=>p.id===presetId);if(p?.repair&&project.formula===p.project.formula){revision++;$<HTMLTextAreaElement>('formula').value=p.repair;run();notice(t('Dimensions repaired. Coefficients and physical assumptions remain unchecked.','量纲已修复，系数和物理假设仍未检查。'));}};
 $('remember').onchange=()=>{remember=$<HTMLInputElement>('remember').checked;if(remember){sync();save();}else storage.remove('dimsleuth.draft.v1');};
 $('forget').onclick=()=>{remember=false;$<HTMLInputElement>('remember').checked=false;storage.remove('dimsleuth.draft.v1');notice(t('Saved draft cleared. Current work is still open.','已清除保存的草稿，当前工作仍保留。'));};
 $('export-project').onclick=()=>{try{sync();download(exportProject(project),'dimsleuth-project.json','application/json');notice(t('Project exported.','项目已导出。'));}catch(e){notice((e as Error).message);}};
 $('export-report').onclick=()=>{try{run();download(exportReport(project,analysis),'dimsleuth-report.html','text/html');notice(t('Standalone report exported.','独立报告已导出。'));}catch(e){notice((e as Error).message);}};
 $('import-project').onclick=()=>$<HTMLInputElement>('file').click();
 $('file').onchange=async()=>{const file=$<HTMLInputElement>('file').files?.[0];if(!file)return;const start=revision,request=++importRequest;try{if(file.size>65536)throw Error(t('Project exceeds 64 KiB.','项目超过 64 KiB。'));const p=importProject(await file.text());if(start!==revision||request!==importRequest)return;load(p);notice(t('Project imported and checked locally.','项目已导入，并在本地检查。'));}catch(e){if(start===revision&&request===importRequest)notice((e as Error).message);}finally{if(request===importRequest)$<HTMLInputElement>('file').value='';}};
}
shell();
// Optional proposed WebMCP API: no network, no persistent grants, feature-detected.
const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>void|Promise<void>}}).modelContext;
if(context?.registerTool){const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'inspect_dimensions',title:'Inspect current dimensional analysis',description:'Read the displayed formula, dimensions and diagnostics. Does not change the project.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');return {formula:analysis.formula,status:analysis.status,diagnostics:analysis.diagnostics,nodes:analysis.nodes};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{/* Unsupported proposal implementations do not affect the workbench. */}}
